spring:
  application:
    name: ERP_Project

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/mydb
    username: mydbid
    password: mydbpw
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mappers/*.xml

server:
  port: 5432